# Generated by Django 5.2.17 on 2026-08-21 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('CAMERA', 'Camera'), ('LAPTOP', 'Laptop'), ('SENSOR', 'Sensor'), ('VEHICLE', 'Vehicle')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CHECKED_OUT', 'Checked Out'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='AVAILABLE', max_length=20)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'category'], name='assets_asse_status_0f8347_idx')],
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('condition_note', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='assets.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='assets.employee')),
            ],
            options={
                'ordering': ['-checked_out_at'],
            },
        ),
        migrations.CreateModel(
            name='OverdueNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='assets.checkout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['returned_at'], name='assets_chec_returne_7df0f2_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['due_at'], name='assets_chec_due_at_5e14d4_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['checked_out_at'], name='assets_chec_checked_f1e045_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['employee', 'returned_at'], name='assets_chec_employe_02b8fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='overduenotice',
            constraint=models.UniqueConstraint(fields=('checkout', 'notice_date'), name='unique_checkout_notice_date'),
        ),
    ]
